services:
  mysql:
    image: mysql:8.4
    container_name: sklr-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: sistem_kelola_les_renang
      MYSQL_USER: sklr_user
      MYSQL_PASSWORD: sklr_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-proot_password"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  mysql_data:
